name: my_formfield
description: A customizable widget for easier and better implementation of the textformfield.
version: 0.0.4
homepage: https://github.com/blaqshyd/my_formfield
repository: https://github.com/blaqshyd/my_formfield

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

